### ISSUE TITLE
SPT tests ignore start symbol

### ISSUE THREAD

**Issue by MeAmAnUsername** [metaborg/spoofax-pie#118] opened 2022-06-08 21:32 UTC
## Summary
SPT tests parse from start symbol defined in `spoofaxc.cfg > parser > default-start-symbol` instead of the start symbol defined in the SPT file.

## What you did
Given these files:
start.sdf3:
```
module start

context-free start-symbols

  Start

lexical start-symbols

  NAT

context-free sorts

  Start
  Exp
  MatchCase

context-free syntax

  Start.Program = Exp

  Exp.Block = [{Exp "\n"}+]

context-free syntax

  Exp.Num = NAT
  Exp.Add = [[Exp] + [Exp]]
  Exp.UnaryMinus = [-[Exp]]
  Exp.BinaryMinus = [[Exp] - [Exp]]

lexical sorts NAT
lexical syntax

  NAT = [0-9]+
  
lexical restrictions

  NAT -/- [0-9]

lexical syntax

  LAYOUT = [\ \n\t\v\f\r]

context-free restrictions

  LAYOUT? -/- [\ \n\t\v\f\r]
```

nat.spt:
```
module lexical/nat
language rpgdsl
start symbol NAT

test negative [[ -4 ]] parse fails
test plus [[ 2 + 4 ]] parse fails
test actual [[ 1 + 2 ]] parse to Program(Add(Num("1"), Num("2")))
```

## What you expected to happen
Tests `negative` and `plus` succeed, i.e. parsing 2 + 4 as a NAT fails. Test `actual` should fail.

## What actually happened
Tests `negative` and `plus` fail, test `actual` succeeds.

## Context
 * Spoofax version: Spoofax-pie 0.19.2
 * Operating system & version: MacOS Mojave, 10.14.6 (18G9323)
 * Java version (if applicable): 11 (bundled with Spoofax)
 * Eclipse version (if applicable): 4.23.0.20220310-1200
 * Gradle version (if applicable): N.A.

**Comment by molenzwiebel** [comment] 2022-06-08 21:39
Duplicate of #48.

**Closed by molenzwiebel** 2022-06-08 21:39 UTC
Labels: C-Bug
