### ISSUE TITLE
Minor: LoggingTracer in Eclipse does not print Unicode 

### ISSUE THREAD

**Issue by Virtlink** [metaborg/spoofax-pie#104] opened 2022-01-18 10:29 UTC
## Summary
The LoggingTracer print an arrow or other symbol at the start of its log lines, but in Eclipse on Windows (on the exam environment) all initial symbols of the log lines appear as question marks.

## Context
* Spoofax version: 0.16.17

**Comment by Gohla** [comment] 2022-01-19 09:25
Duplicate of https://github.com/metaborg/spoofax-pie/issues/57.

**Closed by Gohla** 2022-01-19 09:25 UTC
Labels: C-Bug
