### ISSUE TITLE
Invalid SDF3 source directory expression results in an exception

### ISSUE THREAD

**Issue by molenzwiebel** [metaborg/spoofax-pie#94] opened 2021-11-20 13:20 UTC
## Summary
Setting an invalid `main-source-directory` in spoofaxc.cfg results in an exception.

## What you did
```
sdf3 {
  source = files {
    main-source-directory = 1
  }
}
```

## What you expected to happen
Statix error.

## What actually happened
```
An internal error occurred during: "CFG editor update".
BUG: invalid AST shape, expected string or String/Path/JavaId/SortId/StrategyId application in AST: UInt("1"{TermIndex("eclipse-resource##/dynamix/spoofaxc.cfg",10)}){TermIndex("eclipse-resource##/dynamix/spoofaxc.cfg",11)}
```

## Context
* Spoofax version: devenv, spoofax-pie commit bb75f54bb8df12099ed164889344b79fd296810d
* Operating system & version: Windows

**Comment by Gohla** [comment] 2021-11-23 14:43
There's a whole class of errors like these. The issue is that the code that converts from the CFG to a configuration object runs regardless of whether the static semantics finds any errors. The reason for this is that I'd like to be able to produce a configuration object even in case of errors (i.e., error recovery).

However, that would require many error checks across the entire conversion code, so maybe this was a bad idea and this should be reverted. That would require splitting out errors that are produced on the Java side (e.g., whether directories/files exist) to separate code that *does* run alongside static semantics, and the conversion code which can assume that all checks have passed.

**Comment by Gohla** [comment] 2022-05-18 09:33
Fixed by https://github.com/metaborg/spoofax-pie/commit/b4a108e204842bfa428c1cc339953625c8617b60.

**Closed by Gohla** 2022-05-18 09:33 UTC
Labels: C-Bug
