### ISSUE TITLE
Build initially fails when changing Spoofax 3 language syntax

### ISSUE THREAD

**Issue by Virtlink** [metaborg/spoofax-pie#84] opened 2021-10-21 09:38 UTC
## Summary
When changing the syntax of a Spoofax 3 language, the initial compilation fails. Compiling another time without any changes succeeds. This looks like a dependency issue.

## What you did
I changed the syntax of the `tiger.spoofax3` project. Then I rebuilt Spoofax 3 using `./gradlew buildAll --parallel`. (The project was built previously successfully.)

## What you expected to happen
I expected the build to succeed.

## What actually happened
I got this error:
```
Execution failed for task ':spoofax3.example.root:tiger.spoofax3:compileLanguage'.
> Cannot create parse table; cannot read parse table from resource 'mb-str-classloader-resource##mb/str/target/metaborg/sdf.tbl' or 'mb-str-classloader-resource##mb/str/target/metaborg/table.bin' in classloader resources
```

Invoking `./gradlew buildAll --parallel --info` again fixes the issue.

## Context
* Spoofax version: Spoofax 3 0.15.1 develop
* Operating system & version: macOS 11.6
* Java version: AdoptOpenJDK-11.0.11+9
* Eclipse version: N/A
* Gradle version: 6.9.1

**Comment by Gohla** [comment] 2021-10-21 10:10
I've also encountered this, and I debugged it to be a problem with concurrency. If two Spoofax 3 builds run concurrently via the Gradle plugin, loading things from resources -- like creating a parse table object from its file -- seem to fail with exceptions such as "Stream closed". Here's a build scan that also highlights such a failure (including stacktrace): https://scans.gradle.com/s/t3in64h4747kc/failure#1.

As a workaround, either disable concurrency completely with `--no-parallel --max-workers=1` (I do not recommend this), or just build again, as it is unlikely that both projects will be compiled concurrently again.

I've spent several hours debugging this, but could not find out what the cause is and how to solve it. If you come up with any ideas, please let me know!

**Comment by Gohla** [comment] 2021-11-09 12:17
Should be fixed by https://github.com/metaborg/resource/commit/7263f78a3e0b3190c49d555c397f575fb5e49f4e

**Closed by Gohla** 2021-11-09 12:17 UTC
Labels: C-Bug
